#%RAML 1.0 Extension
title: Digitale Delta - API   RWS Connection Req
version: 2.0
usage: Digital Delta API for RWS systems. Extends DD-API /timeseries endpoint with
       additional request parameters used by MKK-DL.

extends: dd.v20.raml

mediaType: [ application/json ]

uses:
  DD-T: /Libraries/dd-base-types.raml

/timeseries:
  get:
    description: |
        Retrieve timeseries resource.
        Additional request paramters are available to control/extend the output beyound the standard DD-API definition.
    queryParameters:
      fullDdResponse?:
        description:
        type: boolean
        default: true
      responseLocation?:
        description:
        type: string
        example: "locationName:eq:HoekvanHolland:locationNameSpace:eq:NL.RWS.WM:parentName:eq:Rotterdam, displayNameDetail:eq:Hoek van Holland"
      responseObservationType?:
        description:
        type: string
        example: "quantityName:eq:WaterLevel"
      baseUrl?:
        description:
        type: DD-T.Url
        example: "www.rws.nl/dl/dd-oper/2.0/"
